apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:72d60104ad6d435fdd6acf88930328f6ce3993c5597aabf554482d3410becf2a
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
- digest: sha256:3e7c81860d339263b59569353916f790d8926f144db2281a84a393abf26b7c90
  name: quay.io/rhn_gps_njoshi/vote-api
  newName: quay.io/rhn_gps_njoshi/vote-api
- digest: sha256:95c0b41f8c345a1d1bfc84a6aaf50f43fd1dea1ae074b3d202ef1ab1ae0621de
  name: quay.io/rhn_gps_njoshi/vote-ui
  newName: quay.io/rhn_gps_njoshi/vote-ui
